Add failure-reason to fmt-check

diff --git a/.github/workflows/test-fmt-check.yaml b/.github/workflows/test-fmt-check.yaml
--- a/.github/workflows/test-fmt-check.yaml
+++ b/.github/workflows/test-fmt-check.yaml
@@ -12,8 +12,16 @@ jobs:
 
       - name: fmt-check
         uses: ./terraform-fmt-check
+        id: fmt-check
         with:
           path: tests/fmt/canonical
+
+      - name: Check valid
+        run: |
+          if [[ "${{ steps.fmt-check.outputs.failure-reason }}" != "" ]]; then
+            echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
 
   non_canonical_fmt:
     runs-on: ubuntu-latest
@@ -34,5 +42,10 @@ jobs:
         run: |
           if [[ "${{ steps.fmt-check.outcome }}" != "failure" ]]; then
             echo "fmt-check did not fail correctly"
+            exit 1
+          fi
+
+          if [[ "${{ steps.fmt-check.outputs.failure-reason }}" != "check-failed" ]]; then
+            echo "::error:: failure-reason not set correctly"
             exit 1
           fi
