:white_check_mark: Expand tests to cover 0.13

diff --git a/.github/workflows/test-apply.yaml b/.github/workflows/test-apply.yaml
--- a/.github/workflows/test-apply.yaml
+++ b/.github/workflows/test-apply.yaml
@@ -17,7 +17,7 @@ jobs:
         uses: ./terraform-apply
         id: output
         with:
-          path: tests/remote-state/test-bucket
+          path: tests/remote-state/test-bucket_12
           auto_approve: true
 
       - name: Verify outputs
@@ -39,7 +39,7 @@ jobs:
         id: apply
         continue-on-error: true
         with:
-          path: tests/remote-state/test-bucket
+          path: tests/remote-state/test-bucket_12
           auto_approve: true
 
       - name: Check failed to apply
@@ -138,7 +138,7 @@ jobs:
             exit 1
           fi
 
-  backend_config:
+  backend_config_12:
     runs-on: ubuntu-latest
     name: backend_config & backed_config_vars
     env:
@@ -152,19 +152,19 @@ jobs:
       - name: Plan
         uses: ./terraform-plan
         with:
-          path: tests/apply/backend_config
-          backend_config_file: tests/apply/backend_config/backend_config
+          path: tests/apply/backend_config_12
+          backend_config_file: tests/apply/backend_config_12/backend_config
 
       - name: Apply
         uses: ./terraform-apply
-        id: backend_config_file
+        id: backend_config_file_12
         with:
-          path: tests/apply/backend_config
-          backend_config_file: tests/apply/backend_config/backend_config
+          path: tests/apply/backend_config_12
+          backend_config_file: tests/apply/backend_config_12/backend_config
 
       - name: Verify outputs
         run: |
-          if [[ "${{ steps.backend_config_file.outputs.test }}" != "hello" ]]; then
+          if [[ "${{ steps.backend_config_file_12.outputs.test }}" != "hello" ]]; then
             echo "::error:: output from backend_config file not set correctly"
             exit 1
           fi
@@ -172,19 +172,70 @@ jobs:
       - name: Plan
         uses: ./terraform-plan
         with:
-          path: tests/apply/backend_config
+          path: tests/apply/backend_config_12
           backend_config: bucket=terraform-github-actions,key=backend_config,region=eu-west-2
 
       - name: Apply
         uses: ./terraform-apply
-        id: backend_config
+        id: backend_config_12
         with:
-          path: tests/apply/backend_config
+          path: tests/apply/backend_config_12
           backend_config: bucket=terraform-github-actions,key=backend_config,region=eu-west-2
 
       - name: Verify outputs
         run: |
-          if [[ "${{ steps.backend_config.outputs.test }}" != "hello" ]]; then
+          if [[ "${{ steps.backend_config_12.outputs.test }}" != "hello" ]]; then
+            echo "::error:: Output from backend_config not set correctly"
+            exit 1
+          fi
+
+  backend_config_13:
+    runs-on: ubuntu-latest
+    name: backend_config & backed_config_vars
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Plan
+        uses: ./terraform-plan
+        with:
+          path: tests/apply/backend_config_13
+          backend_config_file: tests/apply/backend_config_13/backend_config
+
+      - name: Apply
+        uses: ./terraform-apply
+        id: backend_config_file_13
+        with:
+          path: tests/apply/backend_config_13
+          backend_config_file: tests/apply/backend_config_13/backend_config
+
+      - name: Verify outputs
+        run: |
+          if [[ "${{ steps.backend_config_file_13.outputs.test }}" != "hello" ]]; then
+            echo "::error:: output from backend_config file not set correctly"
+            exit 1
+          fi
+
+      - name: Plan
+        uses: ./terraform-plan
+        with:
+          path: tests/apply/backend_config_13
+          backend_config: bucket=terraform-github-actions,key=backend_config_13,region=eu-west-2
+
+      - name: Apply
+        uses: ./terraform-apply
+        id: backend_config_13
+        with:
+          path: tests/apply/backend_config_13
+          backend_config: bucket=terraform-github-actions,key=backend_config_13,region=eu-west-2
+
+      - name: Verify outputs
+        run: |
+          if [[ "${{ steps.backend_config_13.outputs.test }}" != "hello" ]]; then
             echo "::error:: Output from backend_config not set correctly"
             exit 1
           fi
@@ -261,7 +312,7 @@ jobs:
         uses: ./terraform-apply
         id: output
         with:
-          path: tests/remote-state/test-bucket
+          path: tests/remote-state/test-bucket_12
 
       - name: Verify outputs
         run: |
diff --git a/.github/workflows/test-new-workspace.yaml b/.github/workflows/test-new-workspace.yaml
--- a/.github/workflows/test-new-workspace.yaml
+++ b/.github/workflows/test-new-workspace.yaml
@@ -3,9 +3,9 @@ name: Test terraform-new/destroy-workspace
 on: [pull_request]
 
 jobs:
-  create_workspace:
+  create_workspace_12:
     runs-on: ubuntu-latest
-    name: Workspace tests
+    name: Workspace tests 0.12
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -16,19 +16,19 @@ jobs:
       - name: Create first workspace
         uses: ./terraform-new-workspace
         with:
-          path: tests/new-workspace/remote
+          path: tests/new-workspace/remote_12
           workspace: my-first-workspace
 
       - name: Create first workspace again
         uses: ./terraform-new-workspace
         with:
-          path: tests/new-workspace/remote
+          path: tests/new-workspace/remote_12
           workspace: my-first-workspace
 
       - name: Apply in first workspace
         uses: ./terraform-apply
         with:
-          path: tests/new-workspace/remote
+          path: tests/new-workspace/remote_12
           workspace: my-first-workspace
           var: my_string=hello
           auto_approve: true
@@ -36,39 +36,39 @@ jobs:
       - name: Create a second workspace
         uses: ./terraform-new-workspace
         with:
-          path: tests/new-workspace/remote
+          path: tests/new-workspace/remote_12
           workspace: ${{ github.head_ref }}
 
       - name: Apply in second workspace
         uses: ./terraform-apply
         with:
-          path: tests/new-workspace/remote
+          path: tests/new-workspace/remote_12
           workspace: ${{ github.head_ref }}
           var: my_string=world
           auto_approve: true
 
       - name: Get first workspace outputs
         uses: ./terraform-output
-        id: first
+        id: first_12
         with:
-          path: tests/new-workspace/remote
+          path: tests/new-workspace/remote_12
           workspace: my-first-workspace
 
       - name: Get second workspace outputs
         uses: ./terraform-output
-        id: second
+        id: second_12
         with:
-          path: tests/new-workspace/remote
+          path: tests/new-workspace/remote_12
           workspace: ${{ github.head_ref }}
 
       - name: Verify outputs
         run: |
-          if [[ "${{ steps.first.outputs.my_string }}" != "hello" ]]; then
+          if [[ "${{ steps.first_12.outputs.my_string }}" != "hello" ]]; then
             echo "::error:: output my_string not set correctly for first workspace"
             exit 1
           fi
 
-          if [[ "${{ steps.second.outputs.my_string }}" != "world" ]]; then
+          if [[ "${{ steps.second_12.outputs.my_string }}" != "world" ]]; then
             echo "::error:: output my_string not set correctly for second workspace"
             exit 1
           fi
@@ -76,13 +76,97 @@ jobs:
       - name: Destroy first workspace
         uses: ./terraform-destroy-workspace
         with:
-          path: tests/new-workspace/remote
+          path: tests/new-workspace/remote_12
           workspace: my-first-workspace
           var: my_string=hello
 
       - name: Destroy second workspace
         uses: ./terraform-destroy-workspace
         with:
-          path: tests/new-workspace/remote
+          path: tests/new-workspace/remote_12
+          workspace: ${{ github.head_ref }}
+          var: my_string=world
+
+  create_workspace_13:
+    runs-on: ubuntu-latest
+    name: Workspace tests 0.13
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Create first workspace
+        uses: ./terraform-new-workspace
+        with:
+          path: tests/new-workspace/remote_13
+          workspace: my-first-workspace
+
+      - name: Create first workspace again
+        uses: ./terraform-new-workspace
+        with:
+          path: tests/new-workspace/remote_13
+          workspace: my-first-workspace
+
+      - name: Apply in first workspace
+        uses: ./terraform-apply
+        with:
+          path: tests/new-workspace/remote_13
+          workspace: my-first-workspace
+          var: my_string=hello
+          auto_approve: true
+
+      - name: Create a second workspace
+        uses: ./terraform-new-workspace
+        with:
+          path: tests/new-workspace/remote_13
+          workspace: ${{ github.head_ref }}
+
+      - name: Apply in second workspace
+        uses: ./terraform-apply
+        with:
+          path: tests/new-workspace/remote_13
+          workspace: ${{ github.head_ref }}
+          var: my_string=world
+          auto_approve: true
+
+      - name: Get first workspace outputs
+        uses: ./terraform-output
+        id: first_13
+        with:
+          path: tests/new-workspace/remote_13
+          workspace: my-first-workspace
+
+      - name: Get second workspace outputs
+        uses: ./terraform-output
+        id: second_13
+        with:
+          path: tests/new-workspace/remote_13
+          workspace: ${{ github.head_ref }}
+
+      - name: Verify outputs
+        run: |
+          if [[ "${{ steps.first_13.outputs.my_string }}" != "hello" ]]; then
+            echo "::error:: output my_string not set correctly for first workspace"
+            exit 1
+          fi
+
+          if [[ "${{ steps.second_13.outputs.my_string }}" != "world" ]]; then
+            echo "::error:: output my_string not set correctly for second workspace"
+            exit 1
+          fi
+
+      - name: Destroy first workspace
+        uses: ./terraform-destroy-workspace
+        with:
+          path: tests/new-workspace/remote_13
+          workspace: my-first-workspace
+          var: my_string=hello
+
+      - name: Destroy second workspace
+        uses: ./terraform-destroy-workspace
+        with:
+          path: tests/new-workspace/remote_13
           workspace: ${{ github.head_ref }}
           var: my_string=world
diff --git a/.github/workflows/test-version.yaml b/.github/workflows/test-version.yaml
--- a/.github/workflows/test-version.yaml
+++ b/.github/workflows/test-version.yaml
@@ -113,7 +113,7 @@ jobs:
 
       - name: Check the version
         run: |
-          if [[ "${{ steps.terraform-version.outputs.terraform }}" != *"0.12"* ]]; then
+          if [[ "${{ steps.terraform-version.outputs.terraform }}" != *"0.13"* ]]; then
             echo "::error:: Terraform version not set from required_version"
             exit 1
           fi
@@ -125,26 +125,74 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Test terraform-version
+      - name: Test terraform-version with 0.12
         uses: ./terraform-version
-        id: terraform-version
+        id: terraform-version-12
         with:
-          path: tests/version/providers
+          path: tests/version/providers/0.12
 
       - name: Print the version
         run: |
-          echo "The terraform version was ${{ steps.terraform-version.outputs.terraform }}"
-          echo "The random version was ${{ steps.terraform-version.outputs.random }}"
-          echo "The acme version was ${{ steps.terraform-version.outputs.acme }}"
+          echo "The terraform version was ${{ steps.terraform-version-12.outputs.terraform }}"
+          echo "The random version was ${{ steps.terraform-version-12.outputs.random }}"
+          echo "The acme version was ${{ steps.terraform-version-12.outputs.acme }}"
 
       - name: Check the version
         run: |
-          if [[ "${{ steps.terraform-version.outputs.random }}" != "2.2.0" ]]; then
+          if [[ "${{ steps.terraform-version-12.outputs.random }}" != "2.2.0" ]]; then
             echo "::error:: random provider version has not been set"
             exit 1
           fi
 
-          if [[ -z "${{ steps.terraform-version.outputs.acme }}" ]]; then
+          if [[ -z "${{ steps.terraform-version-12.outputs.acme }}" ]]; then
+            echo "::error:: acme provider version has not been set"
+            exit 1
+          fi
+
+      - name: Test terraform-version with 0.13
+        uses: ./terraform-version
+        id: terraform-version-13
+        with:
+          path: tests/version/providers/0.13
+
+      - name: Print the version
+        run: |
+          echo "The terraform version was ${{ steps.terraform-version-13.outputs.terraform }}"
+          echo "The random version was ${{ steps.terraform-version-13.outputs.random }}"
+          echo "The acme version was ${{ steps.terraform-version-13.outputs.acme }}"
+
+      - name: Check the version
+        run: |
+          if [[ "${{ steps.terraform-version-13.outputs.random }}" != "2.2.0" ]]; then
+            echo "::error:: random provider version has not been set"
+            exit 1
+          fi
+
+          if [[ -z "${{ steps.terraform-version-13.outputs.acme }}" ]]; then
+            echo "::error:: acme provider version has not been set"
+            exit 1
+          fi
+
+      - name: Test terraform-version with 0.11
+        uses: ./terraform-version
+        id: terraform-version-11
+        with:
+          path: tests/version/providers/0.11
+
+      - name: Print the version
+        run: |
+          echo "The terraform version was ${{ steps.terraform-version-11.outputs.terraform }}"
+          echo "The random version was ${{ steps.terraform-version-11.outputs.random }}"
+          echo "The acme version was ${{ steps.terraform-version-11.outputs.acme }}"
+
+      - name: Check the version
+        run: |
+          if [[ "${{ steps.terraform-version-11.outputs.random }}" != "2.2.0" ]]; then
+            echo "::error:: random provider version has not been set"
+            exit 1
+          fi
+
+          if [[ -z "${{ steps.terraform-version-11.outputs.acme }}" ]]; then
             echo "::error:: acme provider version has not been set"
             exit 1
           fi
