Add variables and var_files support for remote operations in terraform-check

diff --git a/.github/workflows/test-remote.yaml b/.github/workflows/test-remote.yaml
--- a/.github/workflows/test-remote.yaml
+++ b/.github/workflows/test-remote.yaml
@@ -61,6 +61,42 @@ jobs:
             exit 1
           fi
 
+      - name: Check no changes
+        uses: ./terraform-check
+        with:
+          path: tests/terraform-cloud
+          workspace: ${{ github.head_ref }}-1
+          backend_config: "token=${{ secrets.TF_API_TOKEN }}"
+          var_file: |
+            tests/terraform-cloud/my_variable.tfvars
+          variables: |
+            from_variables="from_variables"
+
+      - name: Check changes
+        uses: ./terraform-check
+        id: check
+        continue-on-error: true
+        with:
+          path: tests/terraform-cloud
+          workspace: ${{ github.head_ref }}-1
+          backend_config: "token=${{ secrets.TF_API_TOKEN }}"
+          var_file: |
+            tests/terraform-cloud/my_variable.tfvars
+          variables: |
+            from_variables="Changed!"
+
+      - name: Verify changes detected
+        run: |
+          if [[ "${{ steps.check.outcome }}" != "failure" ]]; then
+            echo "Check didn't fail correctly"
+            exit 1
+          fi
+
+          if [[ "${{ steps.check.outputs.failure-reason }}" != "changes-to-apply" ]]; then
+            echo "failure-reason not set correctly"
+            exit 1
+          fi
+
       - name: Destroy workspace
         uses: ./terraform-destroy-workspace
         with:
