Move test to correct job

diff --git a/.github/workflows/test-unlock-state.yaml b/.github/workflows/test-unlock-state.yaml
--- a/.github/workflows/test-unlock-state.yaml
+++ b/.github/workflows/test-unlock-state.yaml
@@ -93,29 +93,6 @@ jobs:
           
           echo 'Lock id is ${{ fromJson(steps.locked-state-destroy.outputs.lock-info).ID }}'
 
-      - name: Try using locked state using terraform-destroy-workspace
-        uses: ./terraform-destroy-workspace
-        id: locked-state-destroy-workspace
-        continue-on-error: true
-        with:
-          path: tests/workflows/test-unlock-state
-
-      - name: Check terraform-destroy-workspace state locked failure-reason
-        run: |
-          if [[ "${{ steps.locked-state-destroy-workspace.outcome }}" != "failure" ]]; then
-            echo "Apply did not fail correctly"
-            exit 1
-          fi
-
-          if [[ "${{ steps.locked-state-destroy-workspace.outputs.failure-reason }}" != "state-locked" ]]; then
-            echo "::error:: failure-reason not set correctly"
-            exit 1
-          fi
-          
-          echo '"${{ steps.locked-state-destroy-workspace.outputs.lock-info }}"'
-          
-          echo 'Lock id is ${{ fromJson(steps.locked-state-destroy-workspace.outputs.lock-info).ID }}'
-
       - name: Unlock the state
         uses: ./terraform-unlock-state
         continue-on-error: true
@@ -199,6 +176,30 @@ jobs:
           echo '"${{ steps.locked-state-workspace.outputs.lock-info }}"'
           
           echo 'Lock id is ${{ fromJson(steps.locked-state-workspace.outputs.lock-info).ID }}'
+
+      - name: Try using locked state using terraform-destroy-workspace
+        uses: ./terraform-destroy-workspace
+        id: locked-state-destroy-workspace
+        continue-on-error: true
+        with:
+          path: tests/workflows/test-unlock-state
+          workspace: hello
+
+      - name: Check terraform-destroy-workspace state locked failure-reason
+        run: |
+          if [[ "${{ steps.locked-state-destroy-workspace.outcome }}" != "failure" ]]; then
+            echo "Apply did not fail correctly"
+            exit 1
+          fi
+
+          if [[ "${{ steps.locked-state-destroy-workspace.outputs.failure-reason }}" != "state-locked" ]]; then
+            echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+          
+          echo '"${{ steps.locked-state-destroy-workspace.outputs.lock-info }}"'
+          
+          echo 'Lock id is ${{ fromJson(steps.locked-state-destroy-workspace.outputs.lock-info).ID }}'
 
       - name: Unlock the state
         uses: ./terraform-unlock-state
