Support OpenTofu

diff --git a/.github/workflows/test-version.yaml b/.github/workflows/test-version.yaml
--- a/.github/workflows/test-version.yaml
+++ b/.github/workflows/test-version.yaml
@@ -638,3 +638,28 @@ jobs:
             echo "::error:: Terraform version not set from .tfswitchrc"
             exit 1
           fi
+
+  opentofu:
+    runs-on: ubuntu-latest
+    name: OPENTOFU_VERSION
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Test terraform-version
+        uses: ./terraform-version
+        id: terraform-version
+        env:
+          OPENTOFU_VERSION: "1.6.0-alpha3"
+        with:
+          path: tests/workflows/test-version/empty
+
+      - name: Print the version
+        run: echo "The terraform version was ${{ steps.terraform-version.outputs.terraform }}"
+
+      - name: Check the version
+        run: |
+          if [[ "${{ steps.terraform-version.outputs.terraform }}" != "1.6.0-alpha3" ]]; then
+            echo "::error:: Terraform version not set from OPENTOFU_VERSION"
+            exit 1
+          fi
