Fix .tool-versions from workspace root

diff --git a/.github/workflows/test-version.yaml b/.github/workflows/test-version.yaml
--- a/.github/workflows/test-version.yaml
+++ b/.github/workflows/test-version.yaml
@@ -103,7 +103,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Test terraform-version
+      - name: Test getting version from .tools-versions
         uses: ./terraform-version
         id: terraform-version
         with:
@@ -111,6 +111,21 @@ jobs:
 
       - name: Print the version
         run: echo "The terraform version was ${{ steps.terraform-version.outputs.terraform }}"
+
+      - name: Check the version
+        run: |
+          if [[ "${{ steps.terraform-version.outputs.terraform }}" != "0.12.11" ]]; then
+            echo "::error:: Terraform version not set from .terraform-version"
+            exit 1
+          fi
+          
+          mv tests/workflows/test-version/asdf/.tool-versions .tool-versions
+
+      - name: Test getting version from root .tools-versions
+        uses: ./terraform-version
+        id: terraform-version
+        with:
+          path: tests/workflows/test-version/asdf
 
       - name: Check the version
         run: |
