Add failure-reason to terraform-check

diff --git a/.github/workflows/test-check.yaml b/.github/workflows/test-check.yaml
--- a/.github/workflows/test-check.yaml
+++ b/.github/workflows/test-check.yaml
@@ -12,8 +12,16 @@ jobs:
 
       - name: Check
         uses: ./terraform-check
+        id: check
         with:
           path: tests/plan/no_changes
+
+      - name: Check failure-reason
+        run: |
+          if [[ "${{ steps.check.outputs.failure-reason }}" != "" ]]; then
+            echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
 
   plan_change_comment:
     runs-on: ubuntu-latest
@@ -29,9 +37,14 @@ jobs:
         with:
           path: tests/plan/plan
 
-      - name: Check invalid
+      - name: Check failure-reason
         run: |
           if [[ "${{ steps.check.outcome }}" != "failure" ]]; then
             echo "Check did not fail correctly"
+            exit 1
+          fi
+
+          if [[ "${{ steps.check.outputs.failure-reason }}" != "changes-to-apply" ]]; then
+            echo "::error:: failure-reason not set correctly"
             exit 1
           fi
