Fix 0.15.4 plan with only changes to outputs

diff --git a/.github/workflows/test-plan.yaml b/.github/workflows/test-plan.yaml
--- a/.github/workflows/test-plan.yaml
+++ b/.github/workflows/test-plan.yaml
@@ -164,6 +164,30 @@ jobs:
             exit 1
           fi
 
+  plan_change_comment_15_4:
+    runs-on: ubuntu-latest
+    name: Change terraform 15.4
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Plan
+        uses: ./terraform-plan
+        id: plan
+        with:
+          path: tests/plan/plan_15_4
+
+      - name: Verify outputs
+        run: |
+          echo "changes=${{ steps.plan.outputs.changes }}"
+
+          if [[ "${{ steps.plan.outputs.changes }}" != "true" ]]; then
+            echo "::error:: output changes not set correctly"
+            exit 1
+          fi
+
   plan_change_comment_latest:
     runs-on: ubuntu-latest
     name: Change latest terraform
