Try loading hcl files in another process
To mitigate hangs from unterminated strings

diff --git a/.github/workflows/test-validate.yaml b/.github/workflows/test-validate.yaml
--- a/.github/workflows/test-validate.yaml
+++ b/.github/workflows/test-validate.yaml
@@ -112,3 +112,17 @@ jobs:
         uses: ./terraform-validate
         with:
           path: tests/workflows/test-validate/unterminated-string
+        id: validate
+        continue-on-error: true
+
+      - name: Check invalid
+        run: |
+          if [[ "${{ steps.validate.outcome }}" != "failure" ]]; then
+            echo "Validate did not fail correctly"
+            exit 1
+          fi
+
+          if [[ "${{ steps.validate.outputs.failure-reason }}" != "validate-failed" ]]; then
+            echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
