Reenable tests for arm64

diff --git a/.github/workflows/test-version.yaml b/.github/workflows/test-version.yaml
--- a/.github/workflows/test-version.yaml
+++ b/.github/workflows/test-version.yaml
@@ -721,57 +721,78 @@ jobs:
             exit 1
           fi
 
-#  arm64:
-#    runs-on: buildjet-2vcpu-ubuntu-2204-arm
-#    name: Version detection on arm
-#    steps:
-#      - name: Checkout
-#        uses: actions/checkout@v4
-#        with:
-#          persist-credentials: false
-#
-#      - name: Version unsupported on arm
-#        uses: ./terraform-version
-#        continue-on-error: true
-#        id: arm-unsupported
-#        env:
-#          TERRAFORM_VERSION: 0.12.0
-#        with:
-#          path: tests/workflows/test-version/empty
-#
-#      - name: Check failed to download unsupported platform
-#        run: |
-#          if [[ "${{ steps.arm-unsupported.outcome }}" != "failure" ]]; then
-#            echo "Did not fail correctly"
-#            exit 1
-#          fi
-#
-#      - name: Version doesn't exist
-#        uses: ./terraform-version
-#        continue-on-error: true
-#        id: no-such-version
-#        with:
-#          path: tests/workflows/test-version/nosuchversion
-#
-#      - name: Check failed to download no such version
-#        run: |
-#          if [[ "${{ steps.no-such-version.outcome }}" != "failure" ]]; then
-#            echo "Did not fail correctly"
-#            exit 1
-#          fi
-#
-#      - name: Test terraform-version
-#        uses: ./terraform-version
-#        id: terraform-version
-#        with:
-#          path: tests/workflows/test-version/tfswitch
-#
-#      - name: Check the version
-#        run: |
-#          if [[ "$DETECTED_TERRAFORM_VERSION" != "1.1.0" ]]; then
-#            echo "::error:: Terraform version not set from .tfswitchrc"
-#            exit 1
-#          fi
+  arm64:
+    runs-on: ubuntu-24.04-arm
+    name: Version detection on arm
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          persist-credentials: false
+
+      - name: Version unsupported on arm
+        uses: ./terraform-version
+        continue-on-error: true
+        id: arm-unsupported
+        env:
+          TERRAFORM_VERSION: 0.12.0
+        with:
+          path: tests/workflows/test-version/empty
+
+      - name: Check failed to download unsupported platform
+        env:
+          OUTCOME: ${{ steps.arm-unsupported.outcome }}
+        run: |
+          if [[ "$OUTCOME" != "failure" ]]; then
+            echo "Did not fail correctly"
+            exit 1
+          fi
+
+      - name: Version doesn't exist
+        uses: ./terraform-version
+        continue-on-error: true
+        id: no-such-version
+        with:
+          path: tests/workflows/test-version/nosuchversion
+
+      - name: Check failed to download no such version
+        env:
+          OUTCOME: ${{ steps.no-such-version.outcome }}
+        run: |
+          if [[ "$OUTCOME" != "failure" ]]; then
+            echo "Did not fail correctly"
+            exit 1
+          fi
+
+      - name: Test terraform-version
+        uses: ./terraform-version
+        id: terraform-version
+        with:
+          path: tests/workflows/test-version/tfswitch
+
+      - name: Check the version
+        env:
+          DETECTED_TERRAFORM_VERSION: ${{ steps.terraform-version.outputs.terraform }}
+        run: |
+          if [[ "$DETECTED_TERRAFORM_VERSION" != "1.1.0" ]]; then
+            echo "::error:: Terraform version not set from .tfswitchrc"
+            exit 1
+          fi
+
+      - name: Test tofu-version
+        uses: ./tofu-version
+        id: tofu-version
+        with:
+          path: tests/workflows/test-version/tofuenv
+
+      - name: Check the version
+        env:
+          DETECTED_TOFU_VERSION: ${{ steps.tofu-version.outputs.tofu }}
+        run: |
+          if [[ "$DETECTED_TOFU_VERSION" != "1.8.5" ]]; then
+            echo "::error:: Terraform version not set from .tfswitchrc"
+            exit 1
+          fi
 
   terraform_opentofu_version:
     runs-on: ubuntu-24.04
