Add workspace lifecycle test for partial cloud config

diff --git a/.github/workflows/test-cloud.yaml b/.github/workflows/test-cloud.yaml
--- a/.github/workflows/test-cloud.yaml
+++ b/.github/workflows/test-cloud.yaml
@@ -270,3 +270,190 @@ jobs:
             echo "Destroy non-existant workspace"
             exit 1
           fi
+
+  cloud:
+    runs-on: ubuntu-latest
+    name: Partial cloud config
+    env:
+      TF_CLOUD_ORGANIZATION: flooktech
+      TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Create a new workspace with no existing workspaces
+        uses: ./terraform-new-workspace
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-1
+
+      - name: Create a new workspace when it doesn't exist
+        uses: ./terraform-new-workspace
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-2
+
+      - name: Create a new workspace when it already exists
+        uses: ./terraform-new-workspace
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-2
+
+      - name: Auto apply workspace
+        uses: ./terraform-apply
+        id: auto_apply
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-1
+          auto_approve: true
+
+      - name: Verify auto_apply terraform outputs
+        run: |
+          if [[ "${{ steps.apply.outputs.len }}" != "5" ]]; then
+            echo "::error:: output not set correctly"
+            exit 1
+          fi
+          
+          if [[ -n "${{ steps.auto_apply.outputs.text_plan_path }}" ]]; then
+            echo "::error:: text_plan_path should not be set"
+            exit 1
+          fi
+
+          if [[ -n "${{ steps.auto_apply.outputs.json_plan_path }}" ]]; then
+            echo "::error:: json_plan_path should not be set"
+            exit 1
+          fi
+
+          echo '${{ steps.auto_apply.outputs.run_id }}'
+          if [[ "${{ steps.auto_apply.outputs.run_id }}" != "run-"* ]]; then
+            echo "::error:: output run_id not set correctly"
+            exit 1
+          fi
+
+      - name: Get outputs
+        uses: ./terraform-output
+        id: output
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-1
+
+      - name: Verify auto_apply terraform outputs with workspace prefix
+        run: |
+          if [[ "${{ steps.output.outputs.len }}" != "5" ]]; then
+            echo "::error:: output not set correctly"
+            exit 1
+          fi
+
+      - name: Check no changes
+        uses: ./terraform-check
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-1
+
+      - name: Check changes
+        uses: ./terraform-check
+        id: check
+        continue-on-error: true
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-1
+          variables: |
+            len=6
+
+      - name: Verify changes detected
+        run: |
+          if [[ "${{ steps.check.outcome }}" != "failure" ]]; then
+            echo "Check didn't fail correctly"
+            exit 1
+          fi
+
+          if [[ "${{ steps.check.outputs.failure-reason }}" != "changes-to-apply" ]]; then
+            echo "failure-reason not set correctly"
+            exit 1
+          fi
+
+      - name: Destroy workspace
+        uses: ./terraform-destroy-workspace
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-1
+
+      - name: Plan workspace
+        uses: ./terraform-plan
+        id: plan
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-2
+
+      - name: Verify plan outputs
+        run: |
+          if [[ "${{ steps.plan.outputs.changes }}" != "true" ]]; then
+            echo "::error:: output changes not set correctly"
+            exit 1
+          fi
+
+          if ! grep -q "Terraform will perform the following actions" '${{ steps.plan.outputs.text_plan_path }}'; then
+            echo "::error:: text_plan_path not set correctly"
+            exit 1
+          fi
+
+          echo '${{ steps.plan.outputs.run_id }}'
+          if [[ "${{ steps.plan.outputs.run_id }}" != "run-"* ]]; then
+            echo "::error:: output run_id not set correctly"
+            exit 1
+          fi
+
+      - name: Apply workspace
+        uses: ./terraform-apply
+        id: apply
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-2
+
+      - name: Verify apply terraform outputs
+        run: |
+          if [[ "${{ steps.apply.outputs.len }}" != "5" ]]; then
+            echo "::error:: Variables not set correctly"
+            exit 1
+          fi
+
+          if ! grep -q "Terraform will perform the following actions" '${{ steps.apply.outputs.text_plan_path }}'; then
+            echo "::error:: text_plan_path not set correctly"
+            exit 1
+          fi
+
+          if [[ -n "${{ steps.apply.outputs.json_plan_path }}" ]]; then
+            echo "::error:: json_plan_path should not be set"
+            exit 1
+          fi
+
+          echo '${{ steps.apply.outputs.run_id }}'
+          if [[ "${{ steps.apply.outputs.run_id }}" != "run-"* ]]; then
+            echo "::error:: output run_id not set correctly"
+            exit 1
+          fi
+
+      - name: Destroy the last workspace
+        uses: ./terraform-destroy-workspace
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-2
+
+      - name: Destroy non-existent workspace
+        uses: ./terraform-destroy-workspace
+        continue-on-error: true
+        id: destroy-non-existant-workspace
+        with:
+          path: tests/workflows/test-cloud/partial
+          workspace: ${{ github.head_ref }}-cloud-1
+
+      - name: Check failed to destroy
+        run: |
+          if [[ "${{ steps.destroy-non-existant-workspace.outcome }}" != "failure" ]]; then
+            echo "Destroy non-existant workspace"
+            exit 1
+          fi
