Use early variables for additional commands
Use early variables for:
- tofu workspace
- tofu show
- tofu validate
- tofu init, even when the backend is not needed

diff --git a/.github/workflows/test-early-eval.yaml b/.github/workflows/test-early-eval.yaml
--- a/.github/workflows/test-early-eval.yaml
+++ b/.github/workflows/test-early-eval.yaml
@@ -10,9 +10,13 @@ jobs:
   s3-backend:
     runs-on: ubuntu-24.04
     name: Plan with early eval
+    permissions:
+      contents: read
+      pull-requests: write
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -21,9 +25,25 @@ jobs:
 
       - name: tofu plan
         uses: ./tofu-plan
+        id: plan
         with:
           path: tests/workflows/test-early-eval/s3
-          add_github_comment: false
+          variables: |
+            passphrase = "tofuqwertyuiopasdfgh"
+
+      - name: Verify outputs
+        env:
+          JSON_PLAN_PATH: ${{ steps.plan.outputs.json_plan_path }}
+        run: |
+          if [[ ! -f "$JSON_PLAN_PATH" ]]; then
+            echo "::error:: json_plan_path not set correctly"
+            exit 1
+          fi
+
+      - name: tofu apply
+        uses: ./tofu-apply
+        with:
+          path: tests/workflows/test-early-eval/s3
           variables: |
             passphrase = "tofuqwertyuiopasdfgh"
 
