Add test for terraform-output on remote workspaces

diff --git a/.github/workflows/test-remote.yaml b/.github/workflows/test-remote.yaml
--- a/.github/workflows/test-remote.yaml
+++ b/.github/workflows/test-remote.yaml
@@ -71,6 +71,21 @@ jobs:
             exit 1
           fi
 
+      - name: Get outputs
+        uses: ./terraform-output
+        id: output
+        with:
+          path: tests/terraform-cloud
+          workspace: ${{ github.head_ref }}-1
+          backend_config: "token=${{ secrets.TF_API_TOKEN }}"
+
+      - name: Verify auto_apply terraform outputs
+        run: |
+          if [[ "${{ steps.output.outputs.default }}" != "default" ]]; then
+            echo "::error:: Variables not set correctly"
+            exit 1
+          fi
+
       - name: Check no changes
         uses: ./terraform-check
         with:
