Add plan-changed failure-reason for terraform-apply

diff --git a/.github/workflows/test-changes-only.yaml b/.github/workflows/test-changes-only.yaml
--- a/.github/workflows/test-changes-only.yaml
+++ b/.github/workflows/test-changes-only.yaml
@@ -31,9 +31,17 @@ jobs:
 
       - name: Apply without changes
         uses: ./terraform-apply
+        id: apply
         with:
           label: no_changes
           path: tests/plan/changes-only
+
+      - name: Check failure-reason
+        run: |
+          if [[ "${{ steps.apply.outputs.failure-reason }}" != "" ]]; then
+            echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
 
   change_then_no_changes:
     runs-on: ubuntu-latest
@@ -84,11 +92,19 @@ jobs:
 
       - name: Apply no changes
         uses: ./terraform-apply
+        id: apply
         with:
           label: change_then_no_changes
           path: tests/plan/changes-only
           variables: |
             cause-changes=false
+
+      - name: Check failure-reason
+        run: |
+          if [[ "${{ steps.apply.outputs.failure-reason }}" != "" ]]; then
+            echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
 
   no_changes_then_changes:
     runs-on: ubuntu-latest
@@ -135,6 +151,11 @@ jobs:
             exit 1
           fi
 
+          if [[ "${{ steps.apply.outputs.failure-reason }}" != "plan-changed" ]]; then
+            echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
   apply_when_plan_has_changed:
     runs-on: ubuntu-latest
     name: Apply should fail if the approved plan has changed
@@ -167,5 +188,10 @@ jobs:
         run: |
           if [[ "${{ steps.apply.outcome }}" != "failure" ]]; then
             echo "Apply did not fail correctly"
+            exit 1
+          fi
+
+          if [[ "${{ steps.apply.outputs.failure-reason }}" != "plan-changed" ]]; then
+            echo "::error:: failure-reason not set correctly"
             exit 1
           fi
