fix: check if plan too long for pr comment

diff --git a/.github/workflows/test-plan.yaml b/.github/workflows/test-plan.yaml
--- a/.github/workflows/test-plan.yaml
+++ b/.github/workflows/test-plan.yaml
@@ -50,6 +50,68 @@ jobs:
           echo "if expression should not have evaluated true"
           exit 1
 
+  too_long:
+    runs-on: ubuntu-latest
+    name: Plan too long
+    env:
+      TF_PLAN_COMMENT_LENGTH: 1
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Plan
+        uses: ./terraform-plan
+        id: plan
+        with:
+          path: tests/workflows/test-plan/plan
+
+      - name: Verify outputs
+        run: |
+          echo "changes=${{ steps.plan.outputs.changes }}"
+
+          if [[ "${{ steps.plan.outputs.changes }}" != "true" ]]; then
+            echo "::error:: output changes not set correctly"
+            exit 1
+          fi
+
+          cat '${{ steps.plan.outputs.json_plan_path }}'
+          if [[ $(jq -r .output_changes.s.actions[0] "${{ steps.plan.outputs.json_plan_path }}") != "create" ]]; then
+            echo "::error:: json_plan_path not set correctly"
+            exit 1
+          fi
+
+          if ! grep -q "Terraform will perform the following actions" '${{ steps.plan.outputs.text_plan_path }}'; then
+            echo "::error:: text_plan_path not set correctly"
+            exit 1
+          fi
+
+          if [[ ${{ steps.plan.outputs.to_add }} -ne 1 ]]; then
+            echo "::error:: to_add not set correctly"
+            exit 1
+          fi
+
+          if [[ ${{ steps.plan.outputs.to_change }} -ne 0 ]]; then
+            echo "::error:: to_change not set correctly"
+            exit 1
+          fi
+
+          if [[ ${{ steps.plan.outputs.to_destroy }} -ne 0 ]]; then
+            echo "::error:: to_destroy not set correctly"
+            exit 1
+          fi
+
+          if [[ -n "${{ steps.apply.outputs.run_id }}" ]]; then
+            echo "::error:: run_id should not be set"
+            exit 1
+          fi
+
+      - name: Test output expressions
+        if: steps.plan.outputs.to_add != 1 || steps.plan.outputs.to_change != 0 || steps.plan.outputs.to_destroy != 0
+        run: |
+          echo "if expression should not have evaluated true"
+          exit 1
+
   no_changes_no_comment:
     runs-on: ubuntu-latest
     name: No changes without comment
