Add underscored output variants
Output names use an annoying mix of underscores and hypens.
This adds an underscored variant for the hypenated variants for consistency.
The hypen outputs are not deprecated and will not be removed.

diff --git a/.github/workflows/test-apply.yaml b/.github/workflows/test-apply.yaml
--- a/.github/workflows/test-apply.yaml
+++ b/.github/workflows/test-apply.yaml
@@ -74,6 +74,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.apply.outcome }}
           FAILURE_REASON: ${{ steps.apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.apply.outputs.failure_reason }}
           JSON_PLAN_PATH: ${{ steps.apply.outputs.json_plan_path }}
           TEXT_PLAN_PATH: ${{ steps.apply.outputs.text_plan_path }}
           RUN_ID: ${{ steps.apply.outputs.run_id }}
@@ -85,6 +86,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -137,6 +143,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.apply.outcome }}
           FAILURE_REASON: ${{ steps.apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.apply.outputs.failure_reason }}
           JSON_PLAN_PATH: ${{ steps.apply.outputs.json_plan_path }}
           TEXT_PLAN_PATH: ${{ steps.apply.outputs.text_plan_path }}
           RUN_ID: ${{ steps.apply.outputs.run_id }}
@@ -148,6 +155,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "apply-failed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -187,6 +199,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.apply.outcome }}
           FAILURE_REASON: ${{ steps.apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.apply.outputs.failure_reason }}
           RUN_ID: ${{ steps.apply.outputs.run_id }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
@@ -196,6 +209,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -1197,6 +1215,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.apply.outcome }}
           FAILURE_REASON: ${{ steps.apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.apply.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Apply did not fail correctly"
@@ -1205,6 +1224,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "plan-changed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
diff --git a/.github/workflows/test-changes-only.yaml b/.github/workflows/test-changes-only.yaml
--- a/.github/workflows/test-changes-only.yaml
+++ b/.github/workflows/test-changes-only.yaml
@@ -48,9 +48,15 @@ jobs:
       - name: Check failure-reason
         env:
           FAILURE_REASON: ${{ steps.apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.apply.outputs.failure_reason }}
         run: |
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -118,9 +124,15 @@ jobs:
       - name: Check failure-reason
         env:
           FAILURE_REASON: ${{ steps.apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.apply.outputs.failure_reason }}
         run: |
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -171,6 +183,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.apply.outcome }}
           FAILURE_REASON: ${{ steps.apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.apply.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Apply did not fail correctly"
@@ -179,6 +192,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "plan-changed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -219,6 +237,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.apply.outcome }}
           FAILURE_REASON: ${{ steps.apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.apply.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Apply did not fail correctly"
@@ -227,5 +246,10 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "plan-changed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
diff --git a/.github/workflows/test-check.yaml b/.github/workflows/test-check.yaml
--- a/.github/workflows/test-check.yaml
+++ b/.github/workflows/test-check.yaml
@@ -25,9 +25,15 @@ jobs:
       - name: Check failure-reason
         env:
           FAILURE_REASON: ${{ steps.check.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.check.outputs.failure_reason }}
         run: |
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -51,6 +57,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.check.outcome }}
           FAILURE_REASON: ${{ steps.check.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.check.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Check did not fail correctly"
@@ -59,5 +66,10 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "changes-to-apply" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
diff --git a/.github/workflows/test-cloud.yaml b/.github/workflows/test-cloud.yaml
--- a/.github/workflows/test-cloud.yaml
+++ b/.github/workflows/test-cloud.yaml
@@ -168,6 +168,7 @@ jobs:
         env:
           CHECK_OUTCOME: ${{ steps.check.outcome }}
           FAILURE_REASON: ${{ steps.check.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.check.outputs.failure_reason }}
         run: |
           if [[ "$CHECK_OUTCOME" != "failure" ]]; then
             echo "Check didn't fail correctly"
@@ -176,6 +177,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "changes-to-apply" ]]; then
             echo "failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -410,6 +416,7 @@ jobs:
         env:
           CHECK_OUTCOME: ${{ steps.check.outcome }}
           FAILURE_REASON: ${{ steps.check.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.check.outputs.failure_reason }}
         run: |
           if [[ "$CHECK_OUTCOME" != "failure" ]]; then
             echo "Check didn't fail correctly"
@@ -418,6 +425,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "changes-to-apply" ]]; then
             echo "failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
diff --git a/.github/workflows/test-fmt-check.yaml b/.github/workflows/test-fmt-check.yaml
--- a/.github/workflows/test-fmt-check.yaml
+++ b/.github/workflows/test-fmt-check.yaml
@@ -25,9 +25,15 @@ jobs:
       - name: Check valid
         env:
           FAILURE_REASON: ${{ steps.fmt-check.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.fmt-check.outputs.failure_reason }}
         run: |
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -52,6 +58,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.fmt-check.outcome }}
           FAILURE_REASON: ${{ steps.fmt-check.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.fmt-check.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "fmt-check did not fail correctly"
@@ -60,5 +67,10 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "check-failed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
diff --git a/.github/workflows/test-refresh.yaml b/.github/workflows/test-refresh.yaml
--- a/.github/workflows/test-refresh.yaml
+++ b/.github/workflows/test-refresh.yaml
@@ -119,6 +119,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.apply.outcome }}
           FAILURE_REASON: ${{ steps.apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.apply.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Apply did not fail correctly"
@@ -127,6 +128,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "plan-changed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
diff --git a/.github/workflows/test-test.yaml b/.github/workflows/test-test.yaml
--- a/.github/workflows/test-test.yaml
+++ b/.github/workflows/test-test.yaml
@@ -27,15 +27,27 @@ jobs:
       - name: Check Passed
         env:
           FAILURE_REASON: ${{ steps.test.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.test.outputs.failure_reason }}
           JUNIT_XML_PATH: ${{ steps.test.outputs.junit-xml-path }}
+          JUNIT_XML_PATH_UNDERSCORE: ${{ steps.test.outputs.junit_xml_path }}
         run: |
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
             exit 1
           fi
 
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
+            exit 1
+          fi
+
           if [[ "$JUNIT_XML_PATH" != "" ]]; then
             echo "::error:: junit-xml-path should not be set"
+            exit 1
+          fi
+
+          if [[ "$JUNIT_XML_PATH_UNDERSCORE" != "$JUNIT_XML_PATH" ]]; then
+            echo "::error:: junit_xml_path not set correctly"
             exit 1
           fi
 
@@ -59,15 +71,27 @@ jobs:
       - name: Check Passed
         env:
           FAILURE_REASON: ${{ steps.test.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.test.outputs.failure_reason }}
           JUNIT_XML_PATH: ${{ steps.test.outputs.junit-xml-path }}
+          JUNIT_XML_PATH_UNDERSCORE: ${{ steps.test.outputs.junit_xml_path }}
         run: |
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
             exit 1
           fi
 
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
+            exit 1
+          fi
+
           if [[ "$JUNIT_XML_PATH" == "" ]]; then
             echo "::error:: junit-xml-path should be set"
+            exit 1
+          fi
+
+          if [[ "$JUNIT_XML_PATH_UNDERSCORE" != "$JUNIT_XML_PATH" ]]; then
+            echo "::error:: junit_xml_path not set correctly"
             exit 1
           fi
 
@@ -101,9 +125,15 @@ jobs:
       - name: Check Passed
         env:
           FAILURE_REASON: ${{ steps.test.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.test.outputs.failure_reason }}
         run: |
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -129,9 +159,15 @@ jobs:
       - name: Check Passed
         env:
           FAILURE_REASON: ${{ steps.test.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.test.outputs.failure_reason }}
         run: |
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -156,6 +192,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.nonexistent_test_dir.outcome }}
           FAILURE_REASON: ${{ steps.nonexistent_test_dir.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.nonexistent_test_dir.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Test did not fail correctly"
@@ -164,6 +201,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "no-tests" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -190,6 +232,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.faulty_filter.outcome }}
           FAILURE_REASON: ${{ steps.faulty_filter.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.faulty_filter.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Test did not fail correctly"
@@ -198,6 +241,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "no-tests" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -224,6 +272,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.failing.outcome }}
           FAILURE_REASON: ${{ steps.failing.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.failing.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Test did not fail correctly"
@@ -232,5 +281,10 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "tests-failed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
diff --git a/.github/workflows/test-unlock-state.yaml b/.github/workflows/test-unlock-state.yaml
--- a/.github/workflows/test-unlock-state.yaml
+++ b/.github/workflows/test-unlock-state.yaml
@@ -42,6 +42,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.failed-apply.outcome }}
           FAILURE_REASON: ${{ steps.failed-apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.failed-apply.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Apply did not fail correctly"
@@ -50,6 +51,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "apply-failed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -66,7 +72,9 @@ jobs:
         env:
           OUTCOME: ${{ steps.locked-state-apply.outcome }}
           FAILURE_REASON: ${{ steps.locked-state-apply.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.locked-state-apply.outputs.failure_reason }}
           LOCK_INFO: ${{ steps.locked-state-apply.outputs.lock-info }}
+          LOCK_INFO_UNDERSCORE: ${{ steps.locked-state-apply.outputs.lock_info }}
           LOCK_ID: ${{ fromJson(steps.locked-state-apply.outputs.lock-info).ID }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
@@ -76,6 +84,16 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "state-locked" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$LOCK_INFO_UNDERSCORE" != "$LOCK_INFO" ]]; then
+            echo "::error:: lock_info not set correctly"
             exit 1
           fi
 
@@ -93,7 +111,9 @@ jobs:
         env:
           OUTCOME: ${{ steps.locked-state-destroy.outcome }}
           FAILURE_REASON: ${{ steps.locked-state-destroy.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.locked-state-destroy.outputs.failure_reason }}
           LOCK_INFO: ${{ steps.locked-state-destroy.outputs.lock-info }}
+          LOCK_INFO_UNDERSCORE: ${{ steps.locked-state-destroy.outputs.lock_info }}
           LOCK_ID: ${{ fromJson(steps.locked-state-destroy.outputs.lock-info).ID }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
@@ -103,6 +123,16 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "state-locked" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$LOCK_INFO_UNDERSCORE" != "$LOCK_INFO" ]]; then
+            echo "::error:: lock_info not set correctly"
             exit 1
           fi
 
@@ -161,6 +191,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.failed-apply-workspace.outcome }}
           FAILURE_REASON: ${{ steps.failed-apply-workspace.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.failed-apply-workspace.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Apply did not fail correctly"
@@ -169,6 +200,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "apply-failed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -186,7 +222,9 @@ jobs:
         env:
           OUTCOME: ${{ steps.locked-state-workspace.outcome }}
           FAILURE_REASON: ${{ steps.locked-state-workspace.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.locked-state-workspace.outputs.failure_reason }}
           LOCK_INFO: ${{ steps.locked-state-workspace.outputs.lock-info }}
+          LOCK_INFO_UNDERSCORE: ${{ steps.locked-state-workspace.outputs.lock_info }}
           LOCK_ID: ${{ fromJson(steps.locked-state-workspace.outputs.lock-info).ID }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
@@ -196,6 +234,16 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "state-locked" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$LOCK_INFO_UNDERSCORE" != "$LOCK_INFO" ]]; then
+            echo "::error:: lock_info not set correctly"
             exit 1
           fi
 
@@ -214,7 +262,9 @@ jobs:
         env:
           OUTCOME: ${{ steps.locked-state-destroy-workspace.outcome }}
           FAILURE_REASON: ${{ steps.locked-state-destroy-workspace.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.locked-state-destroy-workspace.outputs.failure_reason }}
           LOCK_INFO: ${{ steps.locked-state-destroy-workspace.outputs.lock-info }}
+          LOCK_INFO_UNDERSCORE: ${{ steps.locked-state-destroy-workspace.outputs.lock_info }}
           LOCK_ID: ${{ fromJson(steps.locked-state-destroy-workspace.outputs.lock-info).ID }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
@@ -224,6 +274,16 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "state-locked" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$LOCK_INFO_UNDERSCORE" != "$LOCK_INFO" ]]; then
+            echo "::error:: lock_info not set correctly"
             exit 1
           fi
 
diff --git a/.github/workflows/test-validate.yaml b/.github/workflows/test-validate.yaml
--- a/.github/workflows/test-validate.yaml
+++ b/.github/workflows/test-validate.yaml
@@ -25,9 +25,15 @@ jobs:
       - name: Check valid
         env:
           FAILURE_REASON: ${{ steps.validate.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.validate.outputs.failure_reason }}
         run: |
           if [[ "$FAILURE_REASON" != "" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -51,6 +57,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.validate.outcome }}
           FAILURE_REASON: ${{ steps.validate.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.validate.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Validate did not fail correctly"
@@ -59,6 +66,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "validate-failed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -94,6 +106,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.validate.outcome }}
           FAILURE_REASON: ${{ steps.validate.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.validate.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Validate did not fail correctly"
@@ -102,6 +115,11 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "validate-failed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
 
@@ -140,6 +158,7 @@ jobs:
         env:
           OUTCOME: ${{ steps.validate.outcome }}
           FAILURE_REASON: ${{ steps.validate.outputs.failure-reason }}
+          FAILURE_REASON_UNDERSCORE: ${{ steps.validate.outputs.failure_reason }}
         run: |
           if [[ "$OUTCOME" != "failure" ]]; then
             echo "Validate did not fail correctly"
@@ -148,5 +167,10 @@ jobs:
 
           if [[ "$FAILURE_REASON" != "validate-failed" ]]; then
             echo "::error:: failure-reason not set correctly"
+            exit 1
+          fi
+
+          if [[ "$FAILURE_REASON_UNDERSCORE" != "$FAILURE_REASON" ]]; then
+            echo "::error:: failure_reason not set correctly"
             exit 1
           fi
